version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    container_name: ConferencePlanner.BackEnd
    ports:
      - '8000:80'
      - '8001:443'
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ConferencePlanner.BackEnd.pfx
      - "ConnectionStrings:DefaultConnection=Server=sqlserver;Database=BackEnd;MultipleActiveResultSets=true;User Id=myUsername;Password=zWPYAjHbH3W7k#;"
    volumes:
      - '/home/arno/.aspnet/https:/https/'
    depends_on:
      - sqlserver
  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    container_name: ConferencePlanner.FrontEnd
    ports:
      - '8002:80'
      - '8003:443'
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ConferencePlanner.FrontEnd.pfx
      - "ServiceUrl=https://backend:443/"
      - "ConnectionStrings:IdentityDbContextConnection=Server=sqlserver;Database=BackEnd;MultipleActiveResultSets=true;User Id=myUsername;Password=zWPYAjHbH3W7k#;"
    volumes:
      - '/home/arno/.aspnet/https:/https/'
    depends_on:
      - backend
  sqlserver:
    build: SqlServer
    container_name: ConferencePlanner.SqlServer
    ports:
      - '1433:1433'
    environment:
      - 'SA_PASSWORD=z28KH6y^LF()UxQ'
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_PID=Express'
