version: '3.3'
services:
  backend:
    build: BackEnd
    container_name: ConferencePlanner.BackEnd
    ports:
      - '8000:80'
      - '8001:443'
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ConferencePlanner.BackEnd.pfx
    volumes:
      - '/home/arno/.aspnet/https:/https/'    